### ISSUE TITLE
What llvm build does it need?

### ISSUE THREAD

**Issue by vinjn** [baldurk/visor#1]
Hi baldurk, thanks for your amazing works (as always).
Recently I have interests in GPU simulator and visor meets my needs very well.
But I failed to find a llvm build to make it build, can you advise?
Thanks

**Comment by vinjn** [comment]
@baldurk sorry for pinging you :)

**Comment by baldurk** [comment]
The vcxproj points at `T:\llvm-6.0.0.src\` so I guess 6.0, but I wouldn't recommend using this project as it's barely functional and I have no plans to continue with it. [swiftshader](https://github.com/google/swiftshader) does the same thing and is much more complete and actively developed.

**Comment by vinjn** [comment]
Thanks
